### ISSUE TITLE
Import YCB models from HSR gazebo package

### ISSUE THREAD

**Issue by Sushant-Chavan** [b-it-bots/rviz_3d_object_visualizer#1]
The [tmc_wrs_gazebo](https://github.com/hsr-project/tmc_wrs_gazebo) package from Toyota has several YCB model meshes available under the [Creative Commons Attribution 4.0 International license](https://creativecommons.org/licenses/by/4.0/). Importing these models here would make this tool more useful.

The models can be found [here](https://github.com/hsr-project/tmc_wrs_gazebo/tree/master/tmc_wrs_gazebo_worlds/models). When importing the models, we should not forget to add the License information as described [here](https://github.com/hsr-project/tmc_wrs_gazebo/tree/master/tmc_wrs_gazebo_worlds#begins-with-the-name-ycb_).

Related to: #2

**Comment by Sushant-Chavan** [comment]
@alex-mitrevski what do you think about this?

**Comment by alex-mitrevski** [comment]
@Sushant-Chavan I'd say that's a great idea.

**Comment by Sushant-Chavan** [comment]
Is there a subset of the YCB classes that is more relevant to us? AFAIK, I don't think object classes like `chain`, `power_drill` etc are relevant to our use cases right?

**Comment by alex-mitrevski** [comment]
I think it wouldn't hurt to get all available models though. There are definitely objects that aren't really relevant for us, but *maybe* they could be useful for at work scenarios at some point.

**Comment by Sushant-Chavan** [comment]
Definitely, but also setting up the right transforms and scaling for every object mesh will take some time and effort. So I was thinking we could initially focus on the most relevant models and then probably move to the ones we don't encounter that often.

**Comment by alex-mitrevski** [comment]
If that is the case, then you're right. ~But aren't the models already set up correctly in Toyota's repository? Why would we have to change the parameters ourselves?~

Edit: Nevermind, I saw #2, I know what you mean now.

**Comment by Sushant-Chavan** [comment]
All changes were merged into master. Related PR's: #3 #5
